baseURL = "//jamesliu.io/"
languageCode = "en-au"
title = "James Liu"
theme = "paperesque"

[[params.menu]]
  name = "blog"
  url = "posts/"

[[params.topmenu]]
  name = "about"
  url = "about/"

[[params.topmenu]]
  name = "rss"
  url = "posts/index.xml"
