baseURL = "//jamesliu.io/"
languageCode = "en-au"
title = "James Liu"
theme = "hugo-theme-codex"
copyright = "© {year}"

[params]
  dateFormat = "Jan 2 2006"

  twitter = "https://twitter.com/disposedtrolley"
  github = "https://github.com/disposedtrolley"

[markup]
  [markup.highlight]
    codeFences = false

# Navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
